import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Business-Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      {/* Plausible Analytics Script */}
     <head>
  {/* Plausible Analytics */}
  <script
    async
    src="https://plausible.io/js/pa-RL3s3euFZU5ocxUQyi4iN.js"
  />
  <script
    dangerouslySetInnerHTML={{
      __html: `
        window.plausible=window.plausible||function(){
          (plausible.q=plausible.q||[]).push(arguments)
        },
        plausible.init=plausible.init||function(i){plausible.o=i||{}};
        plausible.init();
      `,
    }}
  />
</head>
     
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
